language: android
android:
  components:
    - build-tools-27
    - android-26
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
- chmod +x gradlew
- yes | sdkmanager "platforms;android-27"